export enum UnitConvertionEnum {
  Pa = 'Паскали',
  KgsM2 = 'кгс/м2',
  NM2 = 'Н/м2',
  MmRtSt = 'мм. рт. ст.',
  Bar = 'бар',
  PPSqD = 'фунт-сила на кв. дюйм',
  Dj = 'Дж',
  KgsM = 'кгс∙м',
  LsH = 'л.с. ∙ ч',
  wTH = 'Вт - ч',
  Kal = 'кал',
  Wt = 'Вт',
  KalS = 'кал/с',
  KkalH = 'ккал/ч',
  PoundS = 'фут·фунт/с',
  Ls = 'л.с.',
}
